apiVersion: v1
kind: Service
metadata:
  name: {{ include "mass-calculator-app.fullname" . }}
  labels:
    {{- include "mass-calculator-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
  selector:
    {{- include "mass-calculator-app.selectorLabels" . | nindent 4 }}