apiVersion: v1
kind: Service
metadata:
  name: {{ include "mass-prog.fullname" . }}
  labels:
    {{- include "mass-prog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
  selector:
    {{- include "mass-prog.selectorLabels" . | nindent 4 }}
    # app.kubernetes.io/name: {{ include "mass-prog.name" . }}
    # app.kubernetes.io/instance: {{ .Release.Name }}